'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createContext, useReducer } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const contexto = createContext()

const initialState = {
  token: '',
  tareas: []
}

const reducer = (state, action) => {
  switch(action.type){
    case 'TOKEN':
      return {
        ...state,
        token: action.token
      }
    case 'ADD':
      return {
        ...state,
        tareas: [...state.tareas, action.tarea]
      }
  }
}

export default function RootLayout({ children }) {
  const [state, dispatch] = useReducer(reducer, initialState)

  return (
    <html lang="en">
      <contexto.Provider value={{state, dispatch}}>
        <body
          className={`${geistSans.variable} antialiased`}
        >
          {children}
        </body>
      </contexto.Provider>
    </html>
  );
}
